language: node_js
node_js:
  - "6.10.2"

env:
  global:
    - AWS_REGION=eu-west-1
    - SLS_DEBUG=true

before_install:
  - npm i -g serverless
  - chmod +x deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
